# Generated by Django 3.2.9 on 2021-11-22 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('default', 'Обычный'), ('premium', 'Премиум'), ('vip', 'Вип')], default=None, max_length=15, verbose_name='Статус профиля'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображения для профиля')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='profiles.gallery')),
            ],
            options={
                'verbose_name': 'Изображение для профиля',
                'verbose_name_plural': 'Изображения для профиля',
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='profiles.profile'),
        ),
    ]
