# Generated by Django 3.2.9 on 2021-11-22 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20211122_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Название тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерея профилей', 'verbose_name_plural': 'Галереи профилей'},
        ),
        migrations.CreateModel(
            name='ProfileInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=20, verbose_name='Пол')),
                ('languages', models.CharField(choices=[('russian', 'Русский'), ('english', 'Английский'), ('belarussian', 'Беларусский'), ('francian', 'Французский'), ('italian', 'Итальянский')], max_length=30, verbose_name='Языки')),
                ('education', models.CharField(choices=[('higher', 'Высшее'), ('secondary', 'Среднее'), ('school', 'Школьное')], max_length=30, verbose_name='Образование')),
                ('weight', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Вес')),
                ('description', models.TextField(verbose_name='Описание профиля')),
                ('location', models.CharField(max_length=150, verbose_name='Место расположения')),
                ('registration_date', models.DateTimeField(auto_now=True, verbose_name='Дата регистрации профиля')),
                ('favorites', models.ManyToManyField(related_name='profile_information', to='profiles.Favorites')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_information', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
    ]
