# Generated by Django 3.2.9 on 2021-11-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20211122_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('russian', 'Русский'), ('english', 'Английский'), ('belarussian', 'Беларусский'), ('francian', 'Французский'), ('italian', 'Итальянский')], max_length=15, verbose_name='Язык')),
            ],
        ),
        migrations.AlterModelOptions(
            name='profileinformation',
            options={'verbose_name': 'Информация о профиле', 'verbose_name_plural': 'Информации о профилях'},
        ),
        migrations.RemoveField(
            model_name='profileinformation',
            name='languages',
        ),
        migrations.AddField(
            model_name='profileinformation',
            name='languages',
            field=models.ManyToManyField(to='profiles.Language', verbose_name='Языки'),
        ),
    ]
